
name: SSH-MITM AppImage

on:
  release:
    types: [created]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|ssh-mitm|ssh-mitm|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
